"use client";

import React, { useState, useEffect, useRef, useCallback } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/hooks/useAuth";
import { motion, AnimatePresence } from "framer-motion";
import BriefInput from "@/components/legal/BriefInput";
import JudgmentCard from "@/components/legal/JudgmentCard";
import AnalysisReport from "@/components/legal/AnalysisReport";
import { extractKeywords, analyzeJudgments } from "@/lib/ai/legal-analyzer";
import {
  SAOSJudgmentSummary,
  SAOSJudgmentDetail,
  BriefAnalysis,
  AnalysisReport as AnalysisReportType,
  AnalysisStep,
} from "@/lib/types";

interface LogLine {
  timestamp: string;
  message: string;
  type: "info" | "success" | "warning" | "error";
}

export default function HomePage() {
  const { user, profile, loading, signOut } = useAuth();
  const router = useRouter();

  // Redirect to login if not authenticated
  useEffect(() => {
    if (!loading && !user) {
      router.push("/login");
    }
  }, [user, loading, router]);

  // App State
  const [briefText, setBriefText] = useState("");
  const [step, setStep] = useState<AnalysisStep>("idle");
  const [briefAnalysis, setBriefAnalysis] = useState<BriefAnalysis | null>(null);
  const [searchResults, setSearchResults] = useState<SAOSJudgmentSummary[]>([]);
  const [totalResults, setTotalResults] = useState(0);
  const [judgments, setJudgments] = useState<SAOSJudgmentDetail[]>([]);
  const [report, setReport] = useState<AnalysisReportType | null>(null);
  const [error, setError] = useState<string | null>(null);
  
  // UI States
  const [expandedJudgmentId, setExpandedJudgmentId] = useState<number | null>(null);
  const [logs, setLogs] = useState<LogLine[]>([]);
  
  // Console ref for auto-scrolling
  const consoleEndRef = useRef<HTMLDivElement>(null);

  // Helper to add logs
  const addLog = useCallback(
    (message: string, type: "info" | "success" | "warning" | "error" = "info") => {
      const now = new Date();
      const timestamp = now.toTimeString().split(" ")[0];
      setLogs((prev) => [...prev, { timestamp, message, type }]);
    },
    []
  );

  // Auto-scroll logs
  useEffect(() => {
    consoleEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [logs]);

  // Expand and lazy load judgment details if needed
  const handleExpandJudgment = useCallback(
    async (id: number) => {
      if (expandedJudgmentId === id) {
        setExpandedJudgmentId(null);
        return;
      }

      setExpandedJudgmentId(id);

      // Check if we already have the full text content
      const hasFullText = judgments.some((j) => j.id === id && j.textContent);
      if (!hasFullText) {
        try {
          const res = await fetch(`/api/saos/judgment/${id}`);
          if (res.ok) {
            const detail = await res.json();
            setJudgments((prev) => {
              const index = prev.findIndex((j) => j.id === id);
              if (index > -1) {
                const updated = [...prev];
                updated[index] = detail;
                return updated;
              } else {
                return [...prev, detail];
              }
            });
          } else {
            console.error("Failed to fetch judgment details");
          }
        } catch (err) {
          console.error("Error fetching single judgment:", err);
        }
      }
    },
    [expandedJudgmentId, judgments]
  );

  // Main Analysis Execution
  const handleStartAnalysis = useCallback(async () => {
    if (!briefText.trim()) return;

    // Reset everything
    setStep("extracting_keywords");
    setBriefAnalysis(null);
    setSearchResults([]);
    setTotalResults(0);
    setJudgments([]);
    setReport(null);
    setError(null);
    setExpandedJudgmentId(null);
    setLogs([]);

    addLog("Rozpoczynam przetwarzanie pisma procesowego...", "info");

    try {
      // Step 1: Extract keywords using Gemini
      addLog("Uruchamiam silnik Gemini 2.5 Flash w celu analizy semantycznej pisma...", "info");
      const analysis = await extractKeywords(briefText);
      setBriefAnalysis(analysis);
      addLog(`Sukces: Wyekstrahowano słowa kluczowe: ${analysis.keywords.join(", ")}`, "success");
      addLog(`Zidentyfikowane podstawy prawne: ${analysis.legalBases.join(", ")}`, "info");
      addLog(`Rekomendowany typ sądu: ${analysis.courtType}`, "info");

      // Step 2: Search SAOS API
      setStep("searching_saos");
      addLog("Budowanie zapytań wyszukiwania dla bazy SAOS...", "info");

      let items: SAOSJudgmentSummary[] = [];
      let total = 0;
      let successfulQuery = "";

      // Try search queries generated by Gemini one-by-one (from most specific to more general)
      for (let i = 0; i < analysis.searchQueries.length; i++) {
        const searchQuery = analysis.searchQueries[i];
        addLog(`Próba ${i + 1}/${analysis.searchQueries.length}: Wyszukuję dla zapytania: "${searchQuery}"...`, "info");

        try {
          const response = await fetch(
            `/api/saos/search?query=${encodeURIComponent(searchQuery)}&courtType=${analysis.courtType}&pageSize=8`
          );

          if (response.ok) {
            const searchData = await response.json();
            const queryItems = searchData.items || [];
            const queryTotal = searchData.info?.totalCount || 0;

            if (queryItems.length > 0) {
              items = queryItems;
              total = queryTotal;
              successfulQuery = searchQuery;
              addLog(`Znaleziono ${queryTotal} wyroków dla zapytania: "${searchQuery}"`, "success");
              break;
            } else {
              addLog(`Brak wyników dla zapytania: "${searchQuery}"`, "warning");
            }
          } else {
            addLog(`Błąd API dla zapytania: "${searchQuery}"`, "warning");
          }
        } catch {
          addLog(`Błąd połączenia podczas wyszukiwania dla: "${searchQuery}"`, "warning");
        }
      }

      // Fallback to legal bases if still no results
      if (items.length === 0 && analysis.legalBases && analysis.legalBases.length > 0) {
        const baseQuery = analysis.legalBases[0]
          .replace(/art\./gi, "")
          .replace(/§/g, "")
          .replace(/\./g, "")
          .replace(/k\.c\./gi, "kc")
          .replace(/k\.p\.c\./gi, "kpc")
          .trim();
        
        if (baseQuery) {
          addLog(`Brak wyników dla dedykowanych fraz. Próba awaryjna: wyszukiwanie według podstawy prawnej: "${baseQuery}"...`, "info");
          try {
            const response = await fetch(
              `/api/saos/search?query=${encodeURIComponent(baseQuery)}&courtType=${analysis.courtType}&pageSize=8`
            );
            if (response.ok) {
              const searchData = await response.json();
              items = searchData.items || [];
              total = searchData.info?.totalCount || 0;
              if (items.length > 0) {
                successfulQuery = baseQuery;
                addLog(`Znaleziono ${total} wyroków dla podstawy prawnej: "${baseQuery}"`, "success");
              }
            }
          } catch {
            addLog("Błąd podczas wyszukiwania awaryjnego po podstawie prawnej.", "warning");
          }
        }
      }

      // Fallback to first keyword if still no results
      if (items.length === 0 && analysis.keywords && analysis.keywords.length > 0) {
        const fallbackQuery = analysis.keywords[0];
        addLog(`Próba awaryjna: wyszukiwanie według pierwszego słowa kluczowego: "${fallbackQuery}"...`, "info");
        try {
          const response = await fetch(
            `/api/saos/search?query=${encodeURIComponent(fallbackQuery)}&courtType=${analysis.courtType}&pageSize=8`
          );
          if (response.ok) {
            const searchData = await response.json();
            items = searchData.items || [];
            total = searchData.info?.totalCount || 0;
            if (items.length > 0) {
              successfulQuery = fallbackQuery;
              addLog(`Znaleziono ${total} wyroków dla słowa kluczowego: "${fallbackQuery}"`, "success");
            }
          }
        } catch {
          addLog("Błąd podczas wyszukiwania awaryjnego po słowie kluczowym.", "warning");
        }
      }

      setSearchResults(items);
      setTotalResults(total);

      if (items.length === 0) {
        addLog("Ostateczne ostrzeżenie: Nie znaleziono żadnych pasujących orzeczeń w bazie SAOS dla tej sprawy.", "error");
        addLog("Spróbuj zmodyfikować pismo procesowe lub upewnij się, że zawiera ono polskie przepisy prawne.", "info");
        setStep("done");
        return;
      }

      addLog(`Sukces: Pomyślnie dopasowano wyroki za pomocą zapytania: "${successfulQuery}"`, "success");

      // Step 3: Fetch details for top 5 judgments
      setStep("fetching_judgments");
      const topItems = items.slice(0, 5);
      addLog(`Pobieram pełne uzasadnienia dla top ${topItems.length} wyroków...`, "info");

      const fetchedDetails: SAOSJudgmentDetail[] = [];
      for (const item of topItems) {
        const caseNo = item.courtCases?.[0]?.caseNumber || `#${item.id}`;
        addLog(`Pobieram dane szczegółowe: sygn. ${caseNo}...`, "info");

        try {
          const detailRes = await fetch(`/api/saos/judgment/${item.id}`);
          if (!detailRes.ok) {
            addLog(`Błąd pobierania wyroku ${caseNo}, pomijam.`, "warning");
            continue;
          }

          const detail = await detailRes.json();
          fetchedDetails.push(detail);
          addLog(`Wyrok ${caseNo} pobrany pomyślnie.`, "success");
        } catch {
          addLog(`Błąd połączenia podczas pobierania wyroku ${caseNo}.`, "warning");
        }
      }

      setJudgments(fetchedDetails);

      if (fetchedDetails.length === 0) {
        throw new Error("Nie udało się pobrać treści żadnego ze znalezionych wyroków.");
      }

      // Step 4: AI Context Analysis
      setStep("analyzing");
      addLog(`Przekazuję ${fetchedDetails.length} uzasadnień wyroków do analizy kontekstowej...`, "info");
      addLog("Gemini przeprowadza analizę argumentów, ryzyk procesowych oraz generuje cytaty...", "info");

      const finalReport = await analyzeJudgments(briefText, analysis, fetchedDetails);
      setReport(finalReport);
      
      addLog("Sukces: Generowanie raportu analizy zakończone pomyślnie!", "success");
      setStep("done");
    } catch (err) {
      const errMsg = (err as Error).message || "Nieznany błąd podczas procesu analizy.";
      setError(errMsg);
      addLog(`BŁĄD: ${errMsg}`, "error");
      setStep("error");
    }
  }, [briefText, addLog]);

  // Loading indicator for authentication
  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-bg">
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ repeat: Infinity, duration: 1, ease: "linear" }}
          className="w-8 h-8 border-2 border-accent/30 border-t-accent rounded-full"
        />
      </div>
    );
  }

  if (!user) return null;

  return (
    <div className="min-h-screen bg-bg text-text-primary flex flex-col font-body antialiased relative overflow-hidden">
      {/* Background gradients */}
      <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-accent/5 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-0 right-1/4 w-[500px] h-[500px] bg-success/5 rounded-full blur-[120px] pointer-events-none" />

      {/* Navigation Bar */}
      <header className="border-b border-border bg-bg-surface/50 backdrop-blur-md sticky top-0 z-50 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-accent to-purple-600 flex items-center justify-center font-heading text-lg font-bold text-white shadow-lg shadow-accent/25">
            AV
          </div>
          <div>
            <h1 className="font-heading text-lg leading-tight font-bold text-white tracking-tight">
              Analiza Wyroków AI
            </h1>
            <p className="text-[10px] text-text-secondary leading-none uppercase tracking-wider font-mono">
              System Analizy Orzecznictwa
            </p>
          </div>
        </div>

        <div className="flex items-center gap-4">
          <div className="hidden sm:flex flex-col items-end">
            <span className="text-sm font-medium text-text-primary">
              {profile?.displayName || user.displayName || "Użytkownik"}
            </span>
            <span className="text-[11px] text-text-secondary font-mono">{user.email}</span>
          </div>

          <button
            onClick={() => signOut()}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border text-text-secondary hover:text-text-primary hover:bg-bg-surface-hover transition-all text-xs font-medium cursor-pointer"
          >
            <svg
              className="w-3.5 h-3.5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75"
              />
            </svg>
            Wyloguj
          </button>
        </div>
      </header>

      {/* Main Grid Layout */}
      <main className="flex-1 w-full max-w-7xl mx-auto px-4 py-6 md:px-6 lg:py-10 grid grid-cols-1 lg:grid-cols-12 gap-6 relative z-10">
        
        {/* Left Column: Brief Input, Logs, Search Results */}
        <section className="lg:col-span-6 flex flex-col gap-6">
          <BriefInput
            value={briefText}
            onChange={setBriefText}
            onAnalyze={handleStartAnalysis}
            isAnalyzing={
              step !== "idle" && step !== "done" && step !== "error"
            }
          />

          {/* Real-time System Logs Console */}
          {step !== "idle" && (
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-bg-surface border border-border rounded-2xl p-5 font-mono text-xs"
            >
              <div className="flex items-center justify-between border-b border-border/50 pb-3 mb-3">
                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-accent animate-ping" />
                  <span className="font-semibold text-text-primary text-[11px] uppercase tracking-wider">
                    Logi Systemowe AI & API
                  </span>
                </div>
                <span className="text-[10px] text-text-secondary">
                  Stan: {step}
                </span>
              </div>

              <div className="max-h-48 overflow-y-auto space-y-2 pr-1 scrollbar-thin scrollbar-thumb-border scrollbar-track-transparent">
                {logs.map((log, idx) => (
                  <div key={idx} className="leading-relaxed flex items-start gap-2">
                    <span className="text-text-secondary shrink-0 font-medium select-none">
                      [{log.timestamp}]
                    </span>
                    <span
                      className={
                        log.type === "success"
                          ? "text-success"
                          : log.type === "error"
                          ? "text-error"
                          : log.type === "warning"
                          ? "text-warning"
                          : "text-text-primary"
                      }
                    >
                      {log.message}
                    </span>
                  </div>
                ))}
                <div ref={consoleEndRef} />
              </div>
            </motion.div>
          )}

          {/* Brief Analysis Summary */}
          {briefAnalysis && (
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-bg-surface border border-border rounded-2xl p-5"
            >
              <h3 className="font-heading text-lg text-text-primary mb-2 flex items-center gap-2">
                <span>🔍</span> Wyniki ekstrakcji pisma
              </h3>
              <p className="text-text-secondary text-sm leading-relaxed mb-4">
                {briefAnalysis.summary}
              </p>
              <div className="flex flex-wrap gap-2 mb-3">
                {briefAnalysis.keywords.map((kw) => (
                  <span
                    key={kw}
                    className="px-2.5 py-1 rounded-lg bg-accent-muted border border-accent/25 text-accent text-xs font-medium"
                  >
                    {kw}
                  </span>
                ))}
              </div>
              <div className="flex flex-wrap gap-2 text-xs text-text-secondary">
                <span className="px-2 py-1 rounded-md bg-bg border border-border font-mono">
                  Podstawy prawne: {briefAnalysis.legalBases.join(", ") || "brak wprost"}
                </span>
                <span className="px-2 py-1 rounded-md bg-bg border border-border font-mono">
                  Sąd: {briefAnalysis.courtType}
                </span>
                <span className="px-2 py-1 rounded-md bg-bg border border-border font-mono">
                  Sprawa: {briefAnalysis.caseType}
                </span>
              </div>
            </motion.div>
          )}

          {/* Search Results Orzecznictwo */}
          {(step === "fetching_judgments" || step === "analyzing" || step === "done") &&
            searchResults.length > 0 && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="space-y-4"
              >
                <div className="flex items-center justify-between px-1">
                  <h2 className="font-heading text-xl text-text-primary">
                    Powiązane orzecznictwo SAOS ({totalResults})
                  </h2>
                  <span className="text-xs text-text-secondary font-mono">
                    Pokazuję top {searchResults.length}
                  </span>
                </div>

                <div className="space-y-4">
                  {searchResults.map((result) => {
                    const isPreFetched = judgments.some((j) => j.id === result.id);
                    const tag: "high" | "medium" | "low" = isPreFetched
                      ? "high"
                      : "medium";

                    return (
                      <JudgmentCard
                        key={result.id}
                        judgment={result}
                        isExpanded={expandedJudgmentId === result.id}
                        onExpand={handleExpandJudgment}
                        expandedContent={
                          judgments.find((j) => j.id === result.id)?.textContent
                        }
                        relevanceTag={tag}
                      />
                    );
                  })}
                </div>
              </motion.div>
            )}
        </section>

        {/* Right Column: AI Analysis Report / Welcome Panel */}
        <section className="lg:col-span-6 flex flex-col gap-6">
          <AnimatePresence mode="wait">
            {step === "idle" && (
              <motion.div
                key="welcome"
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.98 }}
                transition={{ duration: 0.3 }}
                className="bg-bg-surface border border-border rounded-2xl p-8 space-y-6 backdrop-blur flex-1 flex flex-col justify-center"
              >
                <div className="w-14 h-14 rounded-2xl bg-accent-muted flex items-center justify-center mb-2 mx-auto">
                  <svg
                    className="w-7 h-7 text-accent"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={1.5}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364-6.364l-.707.707M6.343 17.657l-.707.707m0-12.728l.707.707m12.728 12.728l.707.707M12 8a4 4 0 100 8 4 4 0 000-8z"
                    />
                  </svg>
                </div>

                <div className="text-center space-y-2 max-w-md mx-auto">
                  <h2 className="font-heading text-2xl text-white">
                    Inteligentny Asystent Orzecznictwa
                  </h2>
                  <p className="text-text-secondary text-sm leading-relaxed">
                    Wklej pismo procesowe po lewej stronie, aby system automatycznie odnalazł kluczowe wyroki w bazie SAOS i przeanalizował je pod kątem Twojej sprawy.
                  </p>
                </div>

                <hr className="border-border/50" />

                <div className="space-y-4">
                  <h3 className="text-xs font-semibold text-text-primary uppercase tracking-wider font-mono">
                    Jak to działa:
                  </h3>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="p-4 rounded-xl bg-bg/50 border border-border/50 space-y-1">
                      <div className="text-accent font-semibold text-sm">1. Ekstrakcja AI</div>
                      <p className="text-xs text-text-secondary leading-relaxed">
                        Gemini analizuje pismo, wyodrębniając pojęcia prawne oraz podstawy prawne.
                      </p>
                    </div>

                    <div className="p-4 rounded-xl bg-bg/50 border border-border/50 space-y-1">
                      <div className="text-accent font-semibold text-sm">2. SAOS Querying</div>
                      <p className="text-xs text-text-secondary leading-relaxed">
                        System automatycznie wyszukuje najnowsze wyroki w polskiej bazie orzecznictwa.
                      </p>
                    </div>

                    <div className="p-4 rounded-xl bg-bg/50 border border-border/50 space-y-1">
                      <div className="text-accent font-semibold text-sm">3. Analiza Treści</div>
                      <p className="text-xs text-text-secondary leading-relaxed">
                        Sztuczna inteligencja pobiera uzasadnienia wyroków i wyciąga tezy wspierające oraz ryzyka.
                      </p>
                    </div>

                    <div className="p-4 rounded-xl bg-bg/50 border border-border/50 space-y-1">
                      <div className="text-accent font-semibold text-sm">4. Gotowe Fragmenty</div>
                      <p className="text-xs text-text-secondary leading-relaxed">
                        Otrzymujesz gotowe, profesjonalnie sformułowane cytaty z sygnaturami do wklejenia.
                      </p>
                    </div>
                  </div>
                </div>
              </motion.div>
            )}

            {step === "error" && (
              <motion.div
                key="error"
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.98 }}
                className="bg-bg-surface border border-error/30 rounded-2xl p-6 backdrop-blur flex-1 flex flex-col justify-center items-center text-center space-y-4"
              >
                <div className="w-12 h-12 rounded-xl bg-error-muted flex items-center justify-center">
                  <svg
                    className="w-6 h-6 text-error"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z"
                    />
                  </svg>
                </div>
                <div className="space-y-1">
                  <h2 className="text-lg font-heading font-medium text-white">
                    Wystąpił błąd analizy
                  </h2>
                  <p className="text-text-secondary text-sm max-w-sm">
                    {error || "Nie udało się zakończyć procesu analizy orzecznictwa."}
                  </p>
                </div>
                <button
                  onClick={handleStartAnalysis}
                  className="px-5 py-2 rounded-lg bg-accent text-white text-xs font-semibold hover:bg-accent-hover transition-colors duration-200 cursor-pointer"
                >
                  Spróbuj ponownie
                </button>
              </motion.div>
            )}

            {step !== "idle" && step !== "error" && (
              <motion.div
                key="report-view"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="flex-1 flex flex-col justify-start"
              >
                <AnalysisReport
                  report={report || {
                    summary: "",
                    supportingArguments: [],
                    counterArguments: [],
                    citations: [],
                    recommendation: "",
                  }}
                  isLoading={step !== "done"}
                />
              </motion.div>
            )}
          </AnimatePresence>
        </section>
      </main>
    </div>
  );
}

